spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/cafe_manager
    username: root
    password:
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 10
server:
  port: 8088

